### ISSUE TITLE
Unpublished latest version 2.3.6 of chrome extension

### ISSUE THREAD

**Issue by misak113** [just-paja/nakupuj-bez-andreje#12]
Hi,

nebo vyjímečně tady asi v češtině :) 
Všiml jsem si, že poslední vypublikovaná verze chrome extension ve storu je 2.2.10
![bez-andreje-chrome](https://user-images.githubusercontent.com/1695995/105630292-99726780-5e48-11eb-9866-757412358ec5.png)
Ale zde v repozitáři je již verze 2.3.6 (alpha), která obsahuje zajímavé obohacení funkcionalit (replaceWithLogo, reduceOpacity). 
Bylo by možné ji vypublikovat?

**Comment by just-paja** [comment]
Hi! Určitě to možné je. Díky za motivaci to udělat! :-)

Dotáhnu to z alphy do plné verze.

**Comment by just-paja** [comment]
Publikováno do chrome & firefox store jako verzi 2.3.6.
