### ISSUE TITLE
Nahrazuje srdíčko miniandrejem i u věcí který nejsou jeho.

### ISSUE THREAD

**Issue by gorn** [just-paja/nakupuj-bez-andreje#25]

**Comment by just-paja** [comment]
@gorn , kde bych našel to srdíčko? Prošel jsem si rohlík, košík i makro a žádné srdíčko jsem neviděl. Pomohl by mi přímý odkaz na rozbitou stránku.

**Comment by gorn** [comment]
Zahadne to zaclo fungovat, takze asi nic ...

**Comment by just-paja** [comment]
@gorn, mohlo to kolidovat třeba s nějakým A/B testingem na straně prodejce, ale asi jsem to nechytil včas. Každopádně díky za report a kdyby to zase dělalo neplechu, tak to můžeme odladit.
