### ISSUE TITLE
Andrejovo.cz - Grafické zobrazení vyhledaných firem

### ISSUE THREAD

**Issue by Rum127** [just-paja/nakupuj-bez-andreje#3]
Aktuální grafické zobrazení vyhledaných firem nestačí. 
Proto navrhuji podrobný návrh nového řešení. 
S tímto návrhem ale vzniká mnoho nových úkolů, takže prosím o připomínky a úkolování ;)

![detail firmy](https://user-images.githubusercontent.com/62941585/79615892-001d6480-8104-11ea-92af-46b0a68fbc3e.png)

**Comment by just-paja** [comment]
Podle obrázku bychom přidávali následující:

**1. Logo společnosti**

Ok, proč ne. Dokážu si představit, že to může být užitečné, aby si člověk vizuálně spojil logo s názvem značky.

**2. Fotka sídla společnosti**

Nevidím důvod, proč takovou věc uchovávat.

**3. Název sídla společnosti**

Nevidím důvod, proč takovou věc uchovávat.

**4. Adresu společnosti nebo centrály**

Teoreticky by se mohlo hodit pro identifikaci, ale na co, když máme IČO?

**5. Telefonní číslo**

Nevidím důvod, proč takovou věc uchovávat.

**6. Faxové číslo :-D** 

Nevidím důvod, proč takovou věc uchovávat.

**7. Odkaz na web**

Nevidím důvod, proč takovou věc uchovávat.

**8. Graf vztahů mezi společnostmi**

Nevidím důvod, proč takovou věc uchovávat.

**9. Komponentu, která podle adresy na mapě zobrazuje puntíky reprezentující sídla společností (asi)**

Nevidím důvod, proč takovou věc uchovávat.

**10. Kompletní katalog produktů.**

Neděláme eshop. Nevidím důvod, proč takovou věc uchovávat.

**Comment by Rum127** [comment]
sou

> Podle obrázku bychom přidávali následující:
> 
> **1. Logo společnosti**
> 
> Ok, proč ne. Dokážu si představit, že to může být užitečné, aby si člověk vizuálně spojil logo s názvem značky.
> 
> **2. Fotka sídla společnosti**
> 
> Nevidím důvod, proč takovou věc uchovávat.
> 
> **3. Název sídla společnosti**
> 
> Nevidím důvod, proč takovou věc uchovávat.
> 
> **4. Adresu společnosti nebo centrály**
> 
> Teoreticky by se mohlo hodit pro identifikaci, ale na co, když máme IČO?
> 
> **5. Telefonní číslo**
> 
> Nevidím důvod, proč takovou věc uchovávat.
> 
> **6. Faxové číslo :-D**
> 
> Nevidím důvod, proč takovou věc uchovávat.
> 
> **7. Odkaz na web**
> 
> Nevidím důvod, proč takovou věc uchovávat.
> 
> **8. Graf vztahů mezi společnostmi**
> 
> Nevidím důvod, proč takovou věc uchovávat.
> 
> **9. Komponentu, která podle adresy na mapě zobrazuje puntíky reprezentující sídla společností (asi)**
> 
> Nevidím důvod, proč takovou věc uchovávat.
> 
> **10. Kompletní katalog produktů.**
> 
> Neděláme eshop. Nevidím důvod, proč takovou věc uchovávat.

Dobrá tedy. Původně jsem si přál, aby mělo Andrejovo.cz větší obsah, ale ty si přeješ něco jednoduchého. OK.
Dříve jsi chtěl mít seznam Babišových slibů, pokud si vzpomínám dobře... Stále to platí? 
Rád bych měl něco více propracovaného a chtěl bych mít na webu někde odkaz na fb, počet "lajků" button na sdílení na fb,  Transparentní účet KB a stránku na seznam výpisů z účtu (kvůli finančáku). 
A ještě bych chtěl přidat vyhledávání podle toho čárového kódu, jak se vedla dříve debata ohledně předčíslí.
